# fly.toml app configuration file generated for mrpedrobraga-web-site on 2024-10-25T14:16:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mrpedrobraga-web-site'
primary_region = 'gru'

[build]

[env]
PORT = '8000'
ROCKET_ADDRESS = '0.0.0.0'
ROCKET_PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
