{
	"version": 1509191827,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/control-sheet0.png",
		"images/control-sheet1.png",
		"images/powerup1-sheet0.png",
		"images/powerup0-sheet0.png",
		"images/coin-sheet0.png",
		"images/rainbow_coin-sheet0.png",
		"images/powerup2-sheet0.png",
		"images/jump_effect-sheet0.png",
		"images/mainchar-sheet0.png",
		"images/mainchar-sheet1.png",
		"images/slime-sheet0.png",
		"images/woogy-sheet0.png",
		"images/zapper-sheet0.png",
		"images/zapper-sheet1.png",
		"images/dimmo-sheet0.png",
		"images/dimmo-sheet1.png",
		"images/dimmo-sheet2.png",
		"images/heckon-sheet0.png",
		"images/heckon-sheet1.png",
		"images/heckon-sheet2.png",
		"images/nekito-sheet0.png",
		"images/theanotherpencil-sheet0.png",
		"images/trap-sheet0.png",
		"images/mhealf.png",
		"images/ahealf.png",
		"images/cointext.png",
		"images/lifecounter-sheet0.png",
		"images/exitdoor-sheet0.png",
		"images/exitdoor-sheet1.png",
		"images/cloud-sheet0.png",
		"images/platform-sheet0.png",
		"images/platform-sheet1.png",
		"images/leveldoor-sheet0.png",
		"images/leveldoor-sheet1.png",
		"images/bossdoor-sheet0.png",
		"images/bossdoor-sheet1.png",
		"images/bossdoor-sheet2.png",
		"images/grayracoon-sheet0.png",
		"images/grayracoon-sheet1.png",
		"images/background-sheet0.png",
		"images/background-sheet1.png",
		"images/cavestart.png",
		"images/eclipsesun-sheet0.png",
		"images/eclipsemoon-sheet0.png",
		"images/eclipseboss-sheet0.png",
		"images/tiledbackground.png",
		"images/battle_start-sheet0.png",
		"images/starshooting-sheet0.png",
		"images/starshooting-sheet1.png",
		"images/logo-sheet0.png",
		"images/logo-sheet1.png",
		"images/thepencil-sheet0.png",
		"images/blizzardstar-sheet0.png",
		"images/explosion.png",
		"images/chest-sheet0.png",
		"images/darkeninglayer-sheet0.png",
		"media/jump.ogg",
		"media/coin.ogg",
		"media/sky dance.m4a",
		"media/sky dance.ogg",
		"media/tutorial.m4a",
		"media/tutorial.ogg",
		"media/remix.m4a",
		"media/remix.ogg",
		"media/a new hero.ogg",
		"media/blue.ogg",
		"media/blue_musicbox.ogg",
		"media/boss defeat 1.m4a",
		"media/boss defeat 1.ogg",
		"media/dance-of-dawn.m4a",
		"media/dance-of-dawn.ogg",
		"media/everything blue.m4a",
		"media/everything blue.ogg",
		"media/fanfare2.ogg",
		"media/horn and feather.m4a",
		"media/horn and feather.ogg",
		"media/travelling.ogg",
		"media/blue.m4a",
		"media/sky.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"adapter.js"
	]
}